apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: base
  
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: base
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: base:latest
    source:
      dockerfile: |
        FROM centos:7
        MAINTAINER I.Noguchi
        RUN yum -y install vim
        RUN mkdir -p /var/www/html && chown -R 9999 /var/www
        RUN useradd ichiro -u 9999
        USER 9999
      type: Dockerfile
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: centos7:latest
      type: Docker
    triggers:
    - imageChange: {}
      type: ImageChange
