apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: app

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: app
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: app:latest
    source:
      git:
        uri: https://github.com/IchiroNoguchi/s2itest.git
        ref: master
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: base:latest
      type: Source
    triggers:
    - imageChange: {}
      type: ImageChange
