apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: app
  spec:
    template:
      metadata:
        labels:
          name: app
      spec:
        containers:
        - name: app-latest
          image: app:latest
          ports:
          - containerPort: 9001
            protocol: TCP
    replicas: 1
    selector:
      name: app
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - app-latest
        from:
          kind: ImageStreamTag
          name: app:latest
    - type: ConfigChange

- apiVersion: v1
  kind: Service
  metadata:
    name: app
  spec:
    ports:
    - name: 9001-tcp
      protocol: TCP
      port: 9001
      targetPort: 9001
    selector:
      deploymentconfig: app

- apiVersion: v1
  kind: Route
  metadata:
    name: app-route
  spec:
    host: eplite.project01.oso.example.com
    to:
      kind: Service
      name: app
