apiVersion: v1
kind: BuildConfig
metadata:
  name: s2itest
spec:
  output:
    to:
      kind: ImageStreamTag
      name: s2itest:latest
  source:
    git:
      uri: https://github.com/IchiroNoguchi/s2itest
      ref: master
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: centos7:latest
    type: Source
  triggers:
  - imageChange: {}
    type: ImageChange

